#!/usr/bin/env bash
#
# Title:      rclone updater
# GNU:        General Public License v3.0
################################################################################

source /opt/mhs/lib/menu/functions/update.sh

sudocheck
rcloneupdate
exitcheck
