---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'ddclient'
        intport: '0'
        extport: '0'
        image: 'linuxserver/ddclient'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/mhs/lib/apps-community/apps/_core.yml'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'false'

    - name: 'Setting {{pgrole}} Volumes'
      set_fact:
        pg_volumes:
          - '/etc/localtime:/etc/localtime:ro'
          - '/opt/mhs/apps-data/{{pgrole}}:/config'

    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env:
          UID: '1000'
          GID: '1000'
          GIDLIST: '1000'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: mhs
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'
