---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'zoneminder'
        intport: '443'
        extport: '8444'
        intport2: '9000'
        extport2: '9001'
        image: 'dlandon/zoneminder'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/mhs/lib/apps-community/apps/_core.yml'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}{{tldset}}{{cname}}'
          traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'

    - name: 'Setting {{pgrole}} Volumes'
      set_fact:
        pg_volumes:
          - '/opt/mhs/apps-data/{{pgrole}}/config:/config'
          - '/opt/mhs/apps-data/{{pgrole}}/data:/var/cache/zoneminder'
    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env:
          PUID: '99'
          PGID: '100'
          TZ: 'America/New_York'
          SHMEM: '50%'
          INSTALL_HOOK: '0'
          INSTALL_FACE: '0'
          INSTALL_TINY_YOLO: '0'
          INSTALL_YOLO: '0'
          MULTI_PORT_START: '0'
          MULTI_PORT_END: '0'


    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
          - '{{ports.stdout}}{{extport2}}:{{intport2}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: mhs
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'
