---
- name: Install gdriveclean; remove old cronjob
  cron:
    name: 'gdriveclean'
    user: 'root'
    state: absent
  ignore_errors: yes

- name: Install gdriveclean; remove existing unionfs-fuse whiteout files
  file:
    state: absent
    path: '/mnt/move/.unionfs-fuse'

- name: remove gdriveclean; cronjob
  cron:
    name: 'gdriveclean'
    state: absent
  ignore_errors: yes
