---
########################################## Scripts
- name: Check DockerFix Service
  stat:
    path: '/etc/systemd/system/v2docstart.service'
  register: v2docstart

- name: Install Docker Reboot
  template:
    src: v2dockerscript.sh
    dest: /opt/mhs/etc/mhs/v2dockerscript.sh
    force: yes
########################################## Remove Old Services

- name: Remove Old Docker Fix
  file:
    state: absent
    path: /etc/systemd/system/docstart.service

- name: Remove Old Docker File
  file:
    state: absent
    path: /opt/mhs/etc/mhs/docstart.sh

########################################## New Service

- name: Stop If DockerFix Service Running
  systemd: state=stopped name=v2docstart
  when: v2docstart.stat.exists

- name: Install DockerFix Service
  template:
    src: v2docstart.service
    dest: /etc/systemd/system/v2docstart.service
    force: yes

- name: Daemon-Reload
  systemd: state=stopped name=v2docstart daemon_reload=yes enabled=no

- name: Start DockerFix
  systemd: state=started name=v2docstart enabled=yes
