---
- hosts: localhost
  gather_facts: false
  tasks:
    # KEY VARIABLES ################################################################
    - name: Set crontab
      shell: 'cat /tmp/program_var'
      register: pgrole

    - name: Set cron hour
      shell: 'cat /var/mhs/state/cron/cron.hour'
      register: cronhour

    - name: Set cron minute
      shell: 'cat /var/mhs/state/cron/cron.minute'
      register: cronminute

    - name: Set cron day
      shell: 'cat /var/mhs/state/cron/cron.day'
      register: cronday

    # CRON START ###################################################################
    #  - name: Build Cron Job File
    #    shell: echo "ansible-playbook /opt/mhs/lib/core/cron/bcron.yml --extra-vars 'program_var={{pgrole.stdout}}'" > /opt/mhs/etc/mhs/cron/{{pgrole.stdout}}

    - name: Build Cron Job Schedule
      cron:
        name: '{{pgrole.stdout}}'
        weekday: '{{cronday.stdout}}'
        minute: '{{cronminute.stdout}}'
        hour: '{{cronhour.stdout}}'
        user: root
        job: 'echo {{pgrole.stdout}} >/tmp/program_var && bash /opt/mhs/lib/backup-and-restore/pgcron'
        state: present
      become_user: root
