---
- hosts: localhost
  gather_facts: false
  tasks:
    # KEY VARIABLES ################################################################
    - name: Set PGRole
      shell: 'cat /tmp/program_var'
      register: pgrole

    # CRON REMOVE ##################################################################

    - cron:
        name: '{{pgrole.stdout}}'
        state: absent
      ignore_errors: yes
