---
- hosts: localhost
  gather_facts: false
  tasks:

    - name: 'remove Weekly rclone dedupe'
      cron:
        name: 'Weekly rclone dedupe running'
        special_time: 'weekly'
        job: 'bash /opt/mhs/lib/core/rclonededupe/dupe.sh >/dev/null 2>&1'
        state: 'absent'
      ignore_errors: yes
