#!/usr/bin/env bash
#
# docker autoprune unused docker/ volumes
################################################################################
#echo "[$(date)] Docker Cleanup starting." >>/var/mhs/state/docker-cleanup.log
#docker system prune --volumes -a -f >>/var/mhs/state/docker-cleanup.log
#docker image prune -a -f >>/var/mhs/state/docker-cleanup.log
#docker volume rm $(docker volume ls -qf dangling=true) >>/var/mhs/state/docker-cleanup.log
#echo "[$(date)] Docker Cleanup has completed." >>/var/mhs/state/docker-cleanup.log
#########################################
echo "[$(date)] Docker Cleanup starting." >> /var/mhs/state/docker-cleanup.log
docker=$(docker volume ls -qf dangling=true | wc -l)
if [[ "$docker" -eq "1" ]]; then
  if [[ "$docker" -gt "0" ]]; then
    echo "Cleaning up Docker dangling volumes." >> /var/mhs/state/docker-cleanup.log
    docker volume rm $(docker volume ls -qf dangling=true) >> /var/mhs/state/docker-cleanup.log
    #docker image prune -a -f  >>/var/mhs/state/docker-cleanup.log
    docker system prune --volumes -a -f >> /var/mhs/state/docker-cleanup.log
  else
    echo "No Docker dangling volumes found." >> /var/mhs/state/docker-cleanup.log
  fi
fi
echo "[$(date)] Docker Cleanup has completed." >> /var/mhs/state/docker-cleanup.log
