#!/usr/bin/env bash
################################################################################
# MergerFS updater
################################################################################
source /opt/mhs/lib/core/functions/update.sh

sudocheck
mergerfsupdate
exitcheck
