---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: 'Creating Folder - /mnt/{{drive}}'
      file: 'path={{item}} state=directory mode=0755 owner=1000 group=1000'
      with_items:
        - '/mnt/{{drive}}'

    - name: Register hdpath
      shell: 'cat /var/mhs/state/server.hd.path'
      register: hdpath

    - name: Create Basic Directories
      file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000 recurse=true'
      with_items:
        - '/var/mhs/log'
        - '/var/mhs/log/drive'
        - '/var/mhs/log/emergency'
        - '/var/mhs/log/uploader'
        - '/opt/mhs/lib/roles/log'
      ignore_errors: yes

    - name: 'Install - Service {{drive}}'
      template:
        src: '/opt/mhs/lib/uploader/mounts/drive.service'
        dest: '/etc/systemd/system/{{drive}}.service'
        force: yes

    - name: 'Reload Service - {{drive}}'
      systemd:
        daemon_reload: yes
        enabled: yes
        state: reloaded
        name: '{{drive}}'
