---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS ######################################################################
    - name: Check Service's Existance
      stat:
        path: '/etc/systemd/system/plexpatrol.service'
      register: plexpatrol_service
      ignore_errors: yes

    - name: Stop service
      service:
        name: plexpatrol
        state: stopped
      when: plexpatrol_service.stat.exists
      ignore_errors: yes

    - name: Daemon-Plex-Patrol stop
      systemd: state=stopped name=plexpatrol daemon_reload=yes enabled=no
      ignore_errors: yes

    - name: Remove directories
      file: 'path={{item}} state=absent mode=0775 owner=1000 group=1000'
      with_items:
        - '/opt/mhs/apps-data/plexpatrol/'
        - '/var/mhs/state/plexpatrol'
        - '/etc/systemd/system/plexpatrol.service'
